import type { Theme } from "@/lib/types";

export const THEMES: Theme[] = [
  {
    name: "Default Dark",
    fontFamily: "Inter, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#000000",
    slideBackgroundColor: "#111111",
    accentColor: "#3b82f6",
    gradientBackground: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    sidebarColor: "#1a1a1a",
    navbarColor: "#1a1a1a",
    type: "dark",
  },
  {
    name: "Light Mode",
    fontFamily: "Inter, sans-serif",
    fontColor: "#1f2937",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#f9fafb",
    accentColor: "#3b82f6",
    gradientBackground: "linear-gradient(135deg, #f3f4f6 0%, #e5e7eb 100%)",
    sidebarColor: "#f9fafb",
    navbarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Ocean Blue",
    fontFamily: "Inter, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f172a",
    slideBackgroundColor: "#1e293b",
    accentColor: "#0ea5e9",
    gradientBackground: "linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)",
    sidebarColor: "#1e293b",
    navbarColor: "#1e293b",
    type: "dark",
  },
  {
    name: "Forest Green",
    fontFamily: "Inter, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f1419",
    slideBackgroundColor: "#1a2332",
    accentColor: "#10b981",
    gradientBackground: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    sidebarColor: "#1a2332",
    navbarColor: "#1a2332",
    type: "dark",
  },
  {
    name: "Sunset Orange",
    fontFamily: "Inter, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#1a0f0a",
    slideBackgroundColor: "#2d1b0f",
    accentColor: "#f97316",
    gradientBackground: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
    sidebarColor: "#2d1b0f",
    navbarColor: "#2d1b0f",
    type: "dark",
  },
  {
    name: "Purple Haze",
    fontFamily: "Inter, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f0a1a",
    slideBackgroundColor: "#1a0f2d",
    accentColor: "#8b5cf6",
    gradientBackground: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
    sidebarColor: "#1a0f2d",
    navbarColor: "#1a0f2d",
    type: "dark",
  },
  {
    name: "Crimson Red",
    fontFamily: "Inter, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#1a0a0f",
    slideBackgroundColor: "#2d0f1a",
    accentColor: "#ef4444",
    gradientBackground: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    sidebarColor: "#2d0f1a",
    navbarColor: "#2d0f1a",
    type: "dark",
  },
  {
    name: "Minimal White",
    fontFamily: "Georgia, serif",
    fontColor: "#374151",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#ffffff",
    accentColor: "#6b7280",
    gradientBackground: "linear-gradient(135deg, #ffffff 0%, #f3f4f6 100%)",
    sidebarColor: "#f9fafb",
    navbarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Corporate Blue",
    fontFamily: "Arial, sans-serif",
    fontColor: "#1e3a8a",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#f8fafc",
    accentColor: "#1e40af",
    gradientBackground: "linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%)",
    sidebarColor: "#f1f5f9",
    navbarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Nature Green",
    fontFamily: "Verdana, sans-serif",
    fontColor: "#14532d",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#f0fdf4",
    accentColor: "#16a34a",
    gradientBackground: "linear-gradient(135deg, #dcfce7 0%, #bbf7d0 100%)",
    sidebarColor: "#f0fdf4",
    navbarColor: "#ffffff",
    type: "light",
  },
];
