name: CI/CD Pipeline

on:
  push:
    branches: [main, master, dev, development]
  pull_request:
    branches: [main, master, dev, development]
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma client
        run: bunx prisma generate

      - name: Build Next.js
        run: bun run build
        env:
          # Use placeholder values for CI build
          DATABASE_URL: "postgresql://test:test@localhost:5432/test"
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_placeholder"
          CLERK_SECRET_KEY: "sk_test_placeholder"

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: slidefusion:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CLERK_PUBLISHABLE_KEY=pk_test_placeholder
            CLERK_SECRET_KEY=sk_test_placeholder
            DATABASE_URL=postgresql://test:test@localhost:5432/test
